name: action 2 workflow

on: [push]

jobs:
    run-github-action:
        runs-on: ubuntu-latest
        steps:
            - name: action em javasript
              id: greeting
              uses: actions/hello-world-javascript-action@v1
              with:
                who-to-greet: 'Mona the Octocat and lenne'
            - name: Log greeting time
              run: echo "{{ steps.greeting.outputs.time }}"
