name: shell commands

on: [push]

jobs:
    run-shell-commands:
      runs-on: ubuntu-latest
      steps:
      - name: echo a string
        run: echo "hello world of actions"
      - name: multiline echo
        run: |
          echo "first line"
          uname -s
          docker --version
          java --version
      - name: comandos python
        run: |
          import platform
          print(platform.processor())
        shell: python
