name: container

on: push

jobs:
    node-docker:
        runs-on: ubuntu-latest
        container: 
            image: node:alpine:3.14
        steps:
            - name: log node version
              run: |
                  node -v
                  cat /etc/os-release

